const RecurringBill = require("../models/RecurringBill");
const Expense = require("../models/Expense");
const User = require("../models/User");

const calculateNextDueDate = (currentDate, recurrence) => {
  const date = new Date(currentDate);
  switch (recurrence) {
    case 'daily': date.setDate(date.getDate() + 1); break;
    case 'weekly': date.setDate(date.getDate() + 7); break;
    case 'monthly': date.setMonth(date.getMonth() + 1); break;
    case 'yearly': date.setFullYear(date.getFullYear() + 1); break;
  }
  return date;
};

exports.addRecurringBill = async (req, res) => {
  try {
    const { userId, category, amount, description, dueDate, recurrence, reminderInterval } = req.body;
    
    const bill = new RecurringBill({
      userId,
      category,
      amount,
      description,
      dueDate: new Date(dueDate),
      recurrence,
      reminderInterval: reminderInterval || 24,
      status: 'pending'
    });

    const savedBill = await bill.save();
    res.status(201).json(savedBill);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.getRecurringBills = async (req, res) => {
  try {
    const { userId } = req.query;
    if (!userId) return res.status(400).json({ message: "userId is required" });

    const bills = await RecurringBill.find({ userId }).sort({ dueDate: 1 });
    
    // Check for overdue bills
    const updatedBills = await Promise.all(bills.map(async (bill) => {
      if (bill.status === 'pending' && new Date(bill.dueDate) < new Date()) {
        bill.status = 'overdue';
        await bill.save();
      }
      return bill;
    }));

    res.json(updatedBills);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.markAsPaid = async (req, res) => {
  try {
    const { id } = req.params;
    const bill = await RecurringBill.findById(id);
    if (!bill) return res.status(404).json({ message: "Bill not found" });

    // 1. Create a regular Expense
    const expense = new Expense({
      userId: bill.userId,
      category: bill.category,
      amount: bill.amount,
      description: `Recurring bill payment for ${bill.description || bill.category}`,
      date: new Date(),
      paymentMethod: "recurring-bill",
      isRecurring: true,
      autoGenerated: true,
      source: "recurring-bill-checklist"
    });
    await expense.save();

    // 2. Update the RecurringBill
    bill.lastPaidDate = new Date();
    bill.dueDate = calculateNextDueDate(bill.dueDate, bill.recurrence);
    bill.status = 'pending'; // Reset to pending for the next cycle
    await bill.save();

    res.json({ message: "Bill marked as paid", expense, bill });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.deleteRecurringBill = async (req, res) => {
  try {
    const { id } = req.params;
    await RecurringBill.findByIdAndDelete(id);
    res.json({ message: "Recurring bill deleted" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
