const mongoose = require("mongoose");

const expenseSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User"
  },
  type: {
    type: String,
    enum: ['expense', 'income'],
    default: 'expense'
  },
  category: String,
  amount: Number,
  description: String,
  date: Date,
  paymentMethod: String,
  isRecurring: Boolean,
  autoGenerated: {
    type: Boolean,
    default: false
  },
  source: {
    type: String,
    default: 'manual' 
  }
}, { timestamps: true });

module.exports = mongoose.model("Expense", expenseSchema);